# Generated by Django 2.0 on 2019-07-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('commonfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewssandbox.CommonField')),
                ('first_name', models.CharField(help_text='Please enter a first name.', max_length=40)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('attend_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('viewssandbox.commonfield',),
        ),
    ]
