# Generated by Django 2.0 on 2019-07-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewssandbox', '0003_dogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='DogForm',
        ),
    ]
