# Generated by Django 2.0 on 2019-07-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewssandbox', '0004_auto_20190730_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DogForm',
            new_name='DogInfo',
        ),
    ]
