# Generated by Django 2.0 on 2019-09-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewssandbox', '0007_auto_20190808_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'User info'},
        ),
    ]
