# Generated by Django 2.1 on 2020-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewssandbox', '0008_auto_20190906_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Professional')], help_text='Please choose your current position as student or professionsl.', max_length=1, null=True),
        ),
    ]
